### ISSUE TITLE
Npm start shows cannot get /

### ISSUE THREAD

**Issue by Shibu-N** [kimobrian/TwilioReact#2]
I tried working on the code using the procedure from the https://www.twilio.com/blog/2018/03/video-chat-react.html . After cloning the code from the respository, I made an npm install and then when went for the npm start. It display as follows:
![image](https://user-images.githubusercontent.com/32569397/42165830-d5b7193e-7e26-11e8-92db-35dc5dcd3492.png)

Am I missing something here?

**Comment by arseniummm** [comment]
Faced the same issue, it was a problem with react-tap-event-plugin (no longer supported after React 16.4.0 - [link](https://github.com/zilverline/react-tap-event-plugin/issues/121). Delete it from package.json and app.js

**Comment by bubujone35** [comment]
I also face the same issue. I deleted react-tap-event-plugin from package.json and app.js. Any insights?

**Comment by Pratyush2703** [comment]
In the .env file, change DEV to PROD also should work

**Comment by Pratyush2703** [comment]
Here is a full list of things you need to do in case of this issue:

If .env file says "DEV":

`npm install -save react@^16.3.0`
`npm install -save react-dom@^16.3.0`

if .env says "PROD":
to run the script, 

`npm build && node server`

Hopefully my 3 hours of headache can prevent any more of yours 👍

**Comment by Pratyush2703** [comment]
I suggest this issue be closed and another opened to deal with the deprecation of react-tap-event-plugin

**Comment by ZhuoShan** [comment]
I still got the errors after trying solutions above. Has someone found a way to fix it?

**Comment by kimobrian** [comment]
@Pratyush2703 Thanks for always jumping in to help with these issues.

**Comment by Pratyush2703** [comment]
Happy to help 👍

**Comment by AmanSonii** [comment]
> Here is a full list of things you need to do in case of this issue:
> 
> If .env file says "DEV":
> 
> `npm install -save react@^16.3.0`
> `npm install -save react-dom@^16.3.0`
> 
> if .env says "PROD":
> to run the script,
> 
> `npm build && node server`
> 
> Hopefully my 3 hours of headache can prevent any more of yours 👍

It didn't help me. Please suggest something

**Comment by Pratyush2703** [comment]
@AmanSonii  Please Elaborate

**Comment by AmanSonii** [comment]
I have cloned the project successfully but after running the NPM start I got the Cannot GET / message on the browser and localhost:3000 not found.

**Comment by AmanSonii** [comment]
> @AmanSonii Please Elaborate

I have cloned the project successfully but after running the NPM start I got the Cannot GET / message on the browser and localhost:3000 not found.

**Comment by Pratyush2703** [comment]
@AmanSonii Did you change "Dev" to "PROD" in the .env file ?
