### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by mdboyce** [kimobrian/TwilioReact#4]
Hi - after installing all the modules following your instructions and typing npm start the express server starts, the index.html compiles without error but when you load http://localhost:3000 all you get is a blank page.  No errors.  Looking at the page source this is all I see:

<html>
--
  | <head>
  | <meta charset="UTF-8">
  | <title>React-Twilio App</title>
  | </head>
  | <body>
  | <div id="app"></div>
  | <script type="text/javascript" src="/bundle.js?a2e4f72e2cddd745d24b"></script></body>
  | </html>

Please advise.  Thanks!

**Comment by Pratyush2703** [comment]
Any logs on the console in browser/terminal?

**Comment by tymoxx** [comment]
@mdboyce, in **app.js** remove the lines:

```javascript
import injectTapEventPlugin from "react-tap-event-plugin";
injectTapEventPlugin();
```

refer to issue [#9](https://github.com/kimobrian/TwilioReact/issues/9)

**Comment by kimobrian** [comment]
Fixed. It was due to a deprecation issue of `injectTapEventPlugin`.
