### ISSUE TITLE
Dumb question: Mobile App

### ISSUE THREAD

**Issue by jinman** [kimobrian/TwilioReact#5]
Is there a sample Android App that we can use the same using React-Native or something so we can do video chat from Android App to Web React? Also is there a way to annotate a video stream (say person points to something in the video and marks a circle on phone screen) and send that video stream to the web view?

**Comment by Pratyush2703** [comment]
I think you should better direct that question towards StackOverflow.

**Comment by kimobrian** [comment]
@jinman react and RN are not very different so I'm sure it'll work the same with some few changes of the components used.
As for annotating, not sure if Twilio has such features yet but StackOverflow might be a nice place to ask.
